export const NEWS_SOURCES = [
  { id: 'bbc-news', name: 'BBC News', url: 'bbc.co.uk' },
  { id: 'bloomberg', name: 'Bloomberg', url: 'bloomberg.com' },
  { id: 'bleacher-report', name: 'Bleacher Report', url: 'bleacherreport.com' },
  { id: 'business-insider', name: 'Business Insider', url: 'businessinsider.com' },
  { id: 'buzzfeed', name: 'Buzzfeed', url: 'buzzfeed.com' },
  { id: 'cnn', name: 'CNN', url: 'cnn.com' },
  { id: 'espn', name: 'ESPN', url: 'espn.com' },
  { id: 'financial-post', name: 'Financial Post', url: 'financialpost.com' },
  { id: 'fortune', name: 'Fortune', url: 'fortune.com' },
  { id: 'huffington-post', name: 'Huffington Post', url: 'huffpost.com' },
  { id: 'investors-business-daily', name: 'Investors Business Daily', url: 'investors.com' },
  { id: 'national-geographic', name: 'National Geographic', url: 'nationalgeographic.com' },
  { id: 'new-scientist', name: 'New Scientist', url: 'newscientist.com' },
  // { id: 'reuters', name: 'Reuters', url: 'reuters.com' },
  { id: 'the-wall-street-journal', name: 'The Wall Street Journal', url: 'wsj.com' },
  { id: 'time', name: 'Time', url: 'time.com' },
  { id: 'techradar', name: 'TechRadar', url: 'techradar.com' },
  { id: 'techcrunch', name: 'TechCrunch', url: 'techcrunch.com' },
  { id: 'the-verge', name: 'The Verge', url: 'theverge.com' },
  { id: 'wired', name: 'Wired', url: 'wired.com' },
];